
const products=[
{id:1,name:'کیپ اوپتیفاین',cat:'ماینکرفت',price:20000,old:25000,rating:4.9,img:'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=900&q=80',desc:'کیپ محبوب و حرفه‌ای برای ظاهر متفاوت در ماینکرفت.'},
{id:2,name:'Purple Heart Cape',cat:'ماینکرفت',price:1600000,old:1800000,rating:4.8,img:'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',desc:'کیپ خاص Purple Heart با طراحی پریمیوم.'},
{id:3,name:'Mens Cape',cat:'ماینکرفت',price:180000,rating:4.7,img:'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=900&q=80',desc:'یک انتخاب جذاب برای استایل گیمینگ شما.'},
{id:4,name:'Home Cape',cat:'ماینکرفت',price:100000,rating:4.6,img:'https://images.unsplash.com/photo-1605899435973-ca2d1a8861cf?auto=format&fit=crop&w=900&q=80',desc:'طراحی ساده و شیک برای طرفداران سبک مینیمال.'},
{id:5,name:'Copper Cape',cat:'ماینکرفت',price:60000,old:75000,rating:4.8,img:'https://images.unsplash.com/photo-1627856014753-2d2c5d4c7f1b?auto=format&fit=crop&w=900&q=80',desc:'کیپ مسی با ظاهر متفاوت و خاص.'},
{id:6,name:'Builder Cape',cat:'ماینکرفت',price:70000,rating:4.9,img:'https://images.unsplash.com/photo-1547394765-185e1e68f34e?auto=format&fit=crop&w=900&q=80',desc:'مناسب بازیکنان سازنده و عاشق ساخت‌وساز.'}
];
const money=n=>new Intl.NumberFormat('fa-IR').format(n)+' تومان';
const getCart=()=>JSON.parse(localStorage.getItem('mp_cart')||'[]');
const saveCart=c=>{localStorage.setItem('mp_cart',JSON.stringify(c));updateCounts()};
const getFav=()=>JSON.parse(localStorage.getItem('mp_fav')||'[]');
const saveFav=f=>{localStorage.setItem('mp_fav',JSON.stringify(f));updateCounts()};
function toast(t){const e=document.querySelector('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function updateCounts(){const n=getCart().reduce((a,x)=>a+x.qty,0);document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=n);document.querySelectorAll('[data-fav-count]').forEach(e=>e.textContent=getFav().length)}
function addCart(id){let c=getCart(),x=c.find(x=>x.id==id);x?x.qty++:c.push({id,qty:1});saveCart(c);toast('محصول با موفقیت به سبد خرید اضافه شد ✓')}
function toggleFav(id){let f=getFav();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];saveFav(f);toast(f.includes(id)?'به علاقه‌مندی‌ها اضافه شد ♥':'از علاقه‌مندی‌ها حذف شد')}
function productCard(p){const fav=getFav().includes(p.id);return `<article class="product"><div class="pic"><img src="${p.img}" alt="${p.name}">${p.old?'<span class="badge">تخفیف</span>':''}<button class="fav" onclick="toggleFav(${p.id});this.textContent=getFav().includes(${p.id})?'♥':'♡'">${fav?'♥':'♡'}</button></div><div class="body"><span class="cat">${p.cat}</span><h3>${p.name}</h3><div class="rating">★★★★★ <span style="color:#94a5c6">(${p.rating})</span></div><div class="price"><strong>${money(p.price)}</strong>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><div class="card-actions"><a class="btn" href="/product/?id=${p.id}">مشاهده</a><button class="btn primary" onclick="addCart(${p.id})">افزودن به سبد</button></div></div></article>`}
function renderProducts(list,el){if(!el)return;el.innerHTML=list.length?list.map(productCard).join(''):`<div class="empty" style="grid-column:1/-1"><div class="big">⌕</div>محصولی پیدا نشد.</div>`}
function setupShop(){const el=document.querySelector('#products');if(!el)return;let list=[...products];const search=document.querySelector('#search'),sort=document.querySelector('#sort');const run=()=>{let q=search.value.trim();let x=list.filter(p=>(p.name+' '+p.cat).includes(q));if(sort.value==='cheap')x.sort((a,b)=>a.price-b.price);if(sort.value==='expensive')x.sort((a,b)=>b.price-a.price);if(sort.value==='rating')x.sort((a,b)=>b.rating-a.rating);renderProducts(x,el)};search.oninput=run;sort.onchange=run;renderProducts(list,el)}
function setupHome(){renderProducts(products.slice(0,3),document.querySelector('#featured'));renderProducts(products.slice(3),document.querySelector('#latest'))}
function setupProduct(){const id=Number(new URLSearchParams(location.search).get('id')||1),p=products.find(x=>x.id===id)||products[0],el=document.querySelector('#product-detail');el.innerHTML=`<div class="panel" style="display:grid;grid-template-columns:1fr 1fr;gap:28px;align-items:center"><div class="pic" style="height:420px;border-radius:18px"><img src="${p.img}" alt="${p.name}"></div><div><span class="cat">${p.cat}</span><h1>${p.name}</h1><div class="rating">★★★★★ ${p.rating}</div><p style="color:#aebbd2;line-height:2;margin:20px 0">${p.desc}</p><div class="price"><strong style="font-size:30px">${money(p.price)}</strong>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn primary" onclick="addCart(${p.id})">افزودن به سبد خرید</button><button class="btn" onclick="toggleFav(${p.id})">♥ علاقه‌مندی</button></div></div></div>`}
function setupCart(){const el=document.querySelector('#cart');const render=()=>{let c=getCart();if(!c.length){el.innerHTML='<div class="panel empty"><div class="big">🛒</div><h2>سبد خرید خالی است</h2><p>محصولات موردنظرت را به سبد خرید اضافه کن.</p><a class="btn primary" href="/shop/">رفتن به فروشگاه</a></div>';return}let total=0;el.innerHTML='<div class="panel">'+c.map(x=>{let p=products.find(p=>p.id===x.id);total+=p.price*x.qty;return `<div class="cart-row"><img src="${p.img}"><div><b>${p.name}</b><div style="color:#94a5c6;font-size:12px">${money(p.price)}</div></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div><button class="btn" onclick="removeCart(${p.id})">حذف</button></div>`}).join('')+`<div class="totalbox"><span>جمع کل</span><strong>${money(total)}</strong></div><button class="btn primary" style="width:100%;margin-top:15px" onclick="toast('درگاه پرداخت در نسخه دمو آماده اتصال است.')">ادامه و پرداخت</button></div>`};window.changeQty=(id,d)=>{let c=getCart(),x=c.find(x=>x.id===id);x.qty+=d;if(x.qty<=0)c=c.filter(x=>x.id!==id);saveCart(c);render()};window.removeCart=id=>{saveCart(getCart().filter(x=>x.id!==id));render()};render()}
function setupAuth(){const form=document.querySelector('#auth-form');if(!form)return;form.onsubmit=e=>{e.preventDefault();const name=document.querySelector('#name')?.value||'کاربر مارکت پلاس',email=document.querySelector('#email').value;localStorage.setItem('mp_user',JSON.stringify({name,email}));toast('ورود با موفقیت انجام شد ✓');setTimeout(()=>location.href='/account/',500)}}
function setupAccount(){const u=JSON.parse(localStorage.getItem('mp_user')||'null');if(!u){location.href='/login/';return}document.querySelectorAll('[data-user]').forEach(e=>e.textContent=u.name);const c=getCart();document.querySelector('#order-count').textContent=c.length;document.querySelector('#fav-count').textContent=getFav().length;document.querySelector('#logout')?.addEventListener('click',()=>{localStorage.removeItem('mp_user');location.href='/login/'})}
function setupFav(){const el=document.querySelector('#favorites');renderProducts(products.filter(p=>getFav().includes(p.id)),el)}
document.addEventListener('DOMContentLoaded',()=>{updateCounts();setupHome();setupShop();setupProduct();setupCart();setupAuth();setupAccount();setupFav();document.querySelector('#sell-form')?.addEventListener('submit',e=>{e.preventDefault();toast('درخواست ثبت محصول آماده ارسال است. لطفاً از طریق @AminMtx پیام بدهید.');setTimeout(()=>location.href='https://t.me/AminMtx',600)})});
